### PR TITLE
Fix end function callback

### LINKED ISSUE #14: Fix end function callback call

### PR DESCRIPTION
**Pull request by bugagashenkj**
Close #14

### CODE REVIEW

File: lib/writable.js [hunk 1]
```diff
@@ -238,6 +238,7 @@ class Writable extends EventEmitter {
     }
 
     if (chunk) this.write(chunk, encoding, callback);
+    else if (callback) this.once('finish', callback);
```
Comment (lundibundi) [inline lib/writable.js]: The callback must always be called with `'finish'` event, even when the `chunk` is provided.
